apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-basket
spec:
  replicas: {{ .Values.predictivebasket.replicaCount }}
  selector:
    matchLabels:
      app: predictive-basket
  template:
    metadata:
      labels:
        app: predictive-basket
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: predictive-basket
          image: "{{ .Values.predictivebasket.image }}:{{ .Values.tag }}"
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "4096Mi"
              cpu: "1"
